### ISSUE TITLE
Signs Migration Sprint Review #1

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-data-tracker#155] opened 2019-06-26 21:34 UTC
Going over Signs & Markings stand alone application 
[Home page](https://atd.knack.com/signs-markings#home/)

Scheduled: July 2nd @ 10:30 am

Agenda
- [ ] SR to WO
- [ ] Demo of location & assets
- [ ] WO Close, SR Close

**Comment by amenity** [comment] 2019-07-02 18:08
Duplicate of https://github.com/cityofaustin/atd-data-tech/issues/301.

**Closed by amenity** 2019-07-02 18:08 UTC
Labels: Project: Signs Migration, Type: Meeting, Workgroup: SMB
